# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_title',
            new_name='album_title',
        ),
    ]
