# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20160506_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
