# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20160514_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.FloatField(max_length=100),
        ),
    ]
